# Generated by Django 3.0.9 on 2020-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionDate', models.DateField()),
                ('description', models.CharField(max_length=75)),
                ('category', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
