# Generated by Django 3.0.9 on 2020-08-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jit', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.FileField(upload_to='')),
            ],
        ),
    ]
